### ISSUE TITLE
Liquid burnables making ash

### ISSUE THREAD

**Issue by dengamu** [factoriolab/factoriolab#997] opened 2023-02-14 20:53 UTC
**Describe the bug**
Liquids are showing as making ash from the miners.

**To Reproduce**
1. Add Lead ore as a product
2. Select 10 Acetylene to 1 Lead ore recipe
3. View Ash over production

**Expected behavior**
With Fluid mining drill, liquid is used and ore is received. These miners require power instead of a fuel

**Screenshots**
![image](https://user-images.githubusercontent.com/62602738/218860266-7089b98a-4391-4cb4-8bcc-e522381156f3.png).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chromium
 - Version 104.0.5112.114

**Additional context**
After further narrowing down, it seems the liquid is not being turned into ash but that the Fluid mining drill is requiring a solid fuel. This is not the case as described in Expected behavior. I have narrowed this down here: https://factoriolab.github.io/list?z=eJyt081yokAQwPG38UBVUmqyS3JkYPAjEcRlBuFiIXFQs9Go0WQ9.J99-wW2KoeF.lEU09P0DMX79IfX63eWSWfTPHpy3O06x7zyPPWH.xQLdehKvSe-HQuVr2XGhX.HYnjveSe-dS5Uv.12csf1FskiWKh95yRt927xf-IbfItf4M.xS.wKv8Z.wV.hO.xX.N88tKgeqt-IFUpG1cMVpdaoKEZpiVdU3BUTkYgv1EDiRjyghqGQtGGFGkVC7kcycyQ5o6EYibGQLRo9izexQ40ld2yFvPVJyj9PxS-RCyMKITUTmZ.IWLIRW.Ep5AOlAWomPcykRl4LJ6TrXPKMrMhIHSM1ZNgeUIW0VEsb9VGcxFnIQhspfZD0Q1.coY6-kE91kjLnG8JbwsAQqoAwrAkjeaQTwvFSNIRHooBIEWmiCVGCjtFD9ATJ0lP0DJ2jS3SFrtEv6DPxDXGPuM9gysAxeGOwY3jPUK4HZLHJiXRG2pKuSTekW9Ij0yVZl-yB7JFsQ7YnO5J9kF3IPsm-mOX8mpBr8ph8jmxK3pB.kF8wN5hbzB3mHvMD8xPziFlhHKbFrDEbzBazw-wx75gT5gPbxQbYCKuxMXaMfcI-YydYiy2wc2yJXWIb7B77jmy1PWFl7hl7wX5h.2CvFFOKijKgHFKmlJayoKwpXyj3VH0qxbLLcs3ylaagmdPUNCuaN5odLwYX4BQuxEU4jYtxA9wcV-IqXI1b4hrcCnehHdM-0T7TprRz2pK2ot3THmjPrDO2IduEbcWZc5.PL64F1wPXk-cN5B.2Aq.r3XUu.l9quaXJ&v=7#step_92_recipes

**Comment by dcbroad3** [comment] 2023-02-14 21:11
Potentially related to #657, #744, and/or #778

**Comment by dcbroad3** [comment] 2023-02-15 21:02
Closing as a duplicate of #778, I'll ensure it's resolved with those changes.
There is a lot of work to be done with respect to fuel.

**Closed by dcbroad3** 2023-02-15 21:02 UTC
Labels: bug

**Comment by dcbroad3** [comment] 2023-09-05 14:14
Working on support for fluid energy sources, and went to verify this. However, it looks like the fluid mining drill doesn't have a fluid energy source, and it sure seems like the original behavior was correct. I'm seeing that this drill requires a solid fuel in addition to the mining fluid, and can produce the burnt result of the solid fuel.

![image](https://github.com/factoriolab/factoriolab/assets/8430702/f0646bfa-67bc-4431-b8b8-5f8dd8ae62e5)

**Comment by dengamu** [comment] 2023-09-05 18:14
This can just be chalked up to me not being fully aware of how the tool worked at the time of creation of this ticket. MK01 fluid miners require a solid fuel source. MK02+ do not.
