### ISSUE TITLE
Not all ingredients in a recipe are counted in the proliferation

### ISSUE THREAD

**Issue by lildadou** [factoriolab/factoriolab#1176] opened 2023-09-15 21:30 UTC
**Describe the bug**
I built a complex to produce 3 belt mk2 of proliferator mk2 self-proliferated (so sprayed with mk2). The [solution given](https://factoriolab.github.io/list?z=eJwrcPbVMjbWMtbS0nJTS.JQy4zSMox3sgQRelqGakXhIJYxkKjUMogHqgUpSwMKxUfGu6oVA7lOWo5acOCmVmYJAENGE8A_&v=9#0) is 33 mk2 assembler for an expected spray consumption of 220/m. In practice, the total output calculated is the same, but I obtained a consumption of ~290/m by the sprayers.

In fact, the calculation gives (3960/m proliferator mk1 + 1980/m diamonds + 2376 produced proliferator mk2) 8316/m to be sprayed, i.e. 288.75/m proliferator (28.8 spray per proliferator).

It seems that the diamond line has not been counted among the things to spray.

**To Reproduce**

1. Go to [solution given](https://factoriolab.github.io/list?z=eJwrcPbVMjbWMtbS0nJTS.JQy4zSMox3sgQRelqGakXhIJYxkKjUMogHqgUpSwMKxUfGu6oVA7lOWo5acOCmVmYJAENGE8A_&v=9#0)

**Expected behavior**
The solution should be 34 assemblers and a consumption of 297.5/m proliferator mk2 (In practice, I have 306/m but that's another story.)

**Related bug**
#710 
#1177

**Comment by dcbroad3** [comment] 2023-09-15 22:13
It seems more likely this is a duplicate of #1177. I highly doubt the root problem is that some inputs are not being counted as requiring proliferator.

**Comment by lildadou** [comment] 2023-09-15 22:19
> It seems more likely this is a duplicate of #1177. I highly doubt the root problem is that some inputs are not being counted as requiring proliferator.

Your hypothesis predicts 37.8 by proliferator mk2 self-sprayed instead of 28.8.

In other hand (3960/m proliferator mk1 + ~1980/m diamonds~ + 2376 produced proliferator mk) / 28.8 = 220. It's a perfect match.

**Comment by dcbroad3** [comment] 2023-09-15 23:01
I think maybe I see what the confusion is.
The output is not sprayed. Only inputs are sprayed. You're counting the proliferator required to spray the output, but the calculator does not include it.

**Comment by dcbroad3** [comment] 2023-09-15 23:04
(3960 + 1980 + 220) / 28 = 220
This is what the calculator is doing.
Which actually means #1177 is not an issue, the calculator does in fact round down.

**Comment by dcbroad3** [comment] 2023-09-17 17:05
If you want to open a feature request to specify a proliferator that should be allowed to all output products, you're welcome to do so, but this is currently working as intended.

**Closed by dcbroad3** 2023-09-17 17:05 UTC
Labels: bug
