### ISSUE TITLE
[Factorio: Space Age] Feature request: Restrict surfaces used in calculation 

### ISSUE THREAD

**Issue by nicemoreoften** [factoriolab/factoriolab#1571] opened 2024-10-28 04:18 UTC
**Is your feature request related to a problem? Please describe.**
FactorioLab currently picks very bizarre ways of making things in Space Age: [a simple request to produce enough rocket parts to saturate a silo](https://factoriolab.github.io/spa/list?z=eJwlyqEKw0AQhOG3GTHq9qoqxrQQCqkJiS9sORGxFE4UavbZyyVmPjH.R.cfeSFZWNDEx5gbXJVGGlzjG7zQj7jQEJrIitB8spxsB9H1zDW3XHLOCeFNFeFdBo9dtcB707XA97cMX5n9AeE3I5M_&v=11) with only universal and Vulcanus buildings set as defaults leads to the calculator suggesting importing calcite and carbon from space instead of mining them, as well as a bizarre suggestion to import rocket fuel or ammoniacal solution from Aquilo, which leads to a "solution" that spends more rocket fuel than it even makes!

**Describe the solution you'd like**
A way to select surfaces for FactorioLab to consider available, taking into account resources present on each surface and what is legal to build there.

**Describe alternatives you've considered**
- A way to easily disable groups of recipes that are only possible on certain surfaces, rather than selecting them one at a time.
- A simple way to change the recipe used for a specific item directly inside the Factory menu.
- Consideration of at least rocket part costs to launch rockets for importation of items from other planets.

**Comment by dcbroad3** [comment] 2024-10-28 12:05
Duplicate of #1540

**Comment by dcbroad3** [comment] 2024-10-28 12:05
Duplicate of #1540

**Closed by dcbroad3** 2024-10-28 12:05 UTC
Labels: enhancement
