### ISSUE TITLE
Tech tree + enable/disable recipes by tech

### ISSUE THREAD

**Issue by Soul-Burn** [factoriolab/factoriolab#1019] opened 2023-03-01 19:18 UTC
The default setting for production is fully unlocked recipes, the calculator choosing the most advanced recipe.

In large mods, the usual state is somewhere along the tech tree, with less recipes unlocked. This forces the user to select specific recipes.

The suggestion is to have an interface showing the tech tree (also a neat feature by itself, helps planning) and selecting techs that are researched or not. The system will know to research all dependencies on selection, and remove techs depending on it on deselection.

It would be useful if the tree state could be saved, so the player could update it progressively as they progress through the game.

**Comment by dcbroad3** [comment] 2023-03-01 21:15
Duplicate of #347 
Oldest open issue in the repository at this point but I'm hoping to work on this in the current version (2.1).

**Closed by dcbroad3** 2023-03-01 21:15 UTC
Labels: enhancement
