### ISSUE TITLE
Ultracube: Age of Cube

### ISSUE THREAD

**Issue by kienerxyzzy** [factoriolab/factoriolab#1419] opened 2024-06-26 04:29 UTC
[](https://mods.factorio.com/mod/Ultracube)

**Comment by kienerxyzzy** [comment] 2024-06-26 04:31
[https://mods.factorio.com/mod/Ultracube](https://mods.factorio.com/mod/Ultracube)

**Comment by dcbroad3** [comment] 2024-06-26 12:02
Duplicate of #1334, which is closed as not planned. Ultracube enables recipes using lua scripts, which makes it nearly to impossible to parse. If anyone wants to generate Ultracube data by hand, I would consider accepting a PR, but I'm unable to use my data generation tool to do it.

**Comment by dcbroad3** [comment] 2024-06-26 12:03
Duplicate of #1334, which is closed as not planned. Ultracube enables recipes using lua scripts, which makes it nearly to impossible to parse. If anyone wants to generate Ultracube data by hand, I would consider accepting a PR, but I'm unable to use my data generation tool to do it.

**Closed by dcbroad3** 2024-06-26 12:03 UTC
Labels: mod request
