### ISSUE TITLE
Steel plate productivity bonus

### ISSUE THREAD

**Issue by cowchin12** [factoriolab/factoriolab#1570] opened 2024-10-27 19:32 UTC
**Is your feature request related to a problem? Please describe.**
The steel plate productivity research is available in the technology research dialog of the website but selecting it does not affect the calculations done in the planner.

**Describe the solution you'd like**
A similar drop down to the mining productivity should be added to the bonuses section of the planner.

**Comment by dcbroad3** [comment] 2024-10-27 19:37
Duplicate of #1537

**Closed by dcbroad3** 2024-10-27 19:37 UTC
Labels: enhancement
