### ISSUE TITLE
Space Exploration does not work

### ISSUE THREAD

**Issue by IgNaCy07** [factoriolab/factoriolab#1157] opened 2023-09-11 16:08 UTC
When selecting Space Exploration modset (in the intro screen or in the app), the application crashes, i.e. errors out with `TypeError: Cannot read properties of undefined (reading 'file')`

**Comment by dcbroad3** [comment] 2023-09-11 17:51
Someone else reported this error in Discord as well, but I'm unable to reproduce it and they were unable to reproduce it in a private browsing tab. 
I'll take a closer look at this.

**Comment by dcbroad3** [comment] 2023-09-11 18:16
Is there any call stack or details in the browser console that you can share?

**Comment by dcbroad3** [comment] 2023-09-11 19:33
OK, I figured this out. 
The person who reported this issue in Discord posted a stack trace that included the app version: `2.3.29`. In version `2.3.32`, I updated a lot of the data sets to include fluid temperatures, and when testing that data I noticed an issue with an edge case in the code that was not possible to encounter in any of the data sets prior to that version, so I fixed it in the code. 

It appears that if the UI does not load the latest version, it may still load the latest JSON, which caused you to hit this issue which should have been resolved in the code at the same time the JSON was updated. 

Doing a hard refresh of the browser, or maybe even a soft refresh, should force it to update the application to the latest version, and should get you past this error. 

I think the only way to address this problem in a more general sense would be to somehow cache old JSON files by version number, so that each version of the app loads data from the corresponding version, but I seriously hope this is a rare enough issue that isn't necessary.

**Closed by dcbroad3** 2023-09-11 19:33 UTC
Labels: bug

**Comment by dcbroad3** [comment] 2023-09-11 19:36
For anyone curious, the relevant change is [here](https://github.com/factoriolab/factoriolab/pull/1145/files#diff-d161201fb9836f3e17769e207296f74e456abd4c03ae41ccb443ae6644410826). The old code assumed that the output item id from the recipe would also map to an item id. The new JSON includes many different fluid temperatures with various item ids, that all use the same icon id, which caused this bug to surface.
