### ISSUE TITLE
Settings for Different Orders

### ISSUE THREAD

**Issue by MuppetMurderer** [factoriolab/factoriolab#876] opened 2022-11-19 19:10 UTC
It's annoying to try and find an order to make your factories in while having several products, since the order of the tree no longer goes in the order of what's needed. (If you used the older version, you know what order I'm talking about.)

To solve this, there could be order settings that let you change the order, either manually by dragging the steps around, or by having multiple preset orders to choose from, such as the previously mentioned order of what's needed or first doing components then products.

**Comment by dcbroad3** [comment] 2022-11-19 19:19
Somewhat a duplicate of #479 
The order should be the same as the old version, as mentioned in your other issue. Could you highlight an example?

**Comment by dcbroad3** [comment] 2022-12-08 18:03
I would be interested in seeing an example of the difference in sorting between the old version and the new version, but otherwise this is a duplicate of #479. I am willing to reopen the issue if you have further information.

**Closed by dcbroad3** 2022-12-08 18:03 UTC
Labels: enhancement
